# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mock.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmock.proto\"c\n\x0bloadRequest\x12\x0c\n\x04time\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\x12\r\n\x05plate\x18\x03 \x01(\t\x12\r\n\x05model\x18\x04 \x01(\t\x12\x0c\n\x04name\x18\x05 \x01(\t\x12\x0c\n\x04year\x18\x06 \x01(\x05\"\x1f\n\x0cloadResponse\x12\x0f\n\x07message\x18\x01 \x01(\t20\n\x07Sending\x12%\n\x04Send\x12\x0c.loadRequest\x1a\r.loadResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mock_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOADREQUEST._serialized_start=14
  _LOADREQUEST._serialized_end=113
  _LOADRESPONSE._serialized_start=115
  _LOADRESPONSE._serialized_end=146
  _SENDING._serialized_start=148
  _SENDING._serialized_end=196
# @@protoc_insertion_point(module_scope)
